### ISSUE TITLE
Total rotate left functions

### ISSUE THREAD

**Issue by weaversa** [easyaspi314/xxhash-clean#2]
Since this project aims to be "excessively?" clean (which I appreciate) and I imagine folks might even reuse components from here in their own projects, would you be willing to entertain replacing the current definitions of rotate left with ones that avoid undefined behavior?

For example, XXH_rotl32 here:
```
static uint32_t XXH_rotl32(uint32_t const value, uint32_t const amount)
{
    return (value << amount) | (value >> (32 - amount));
}
```

could be replaced by this:
```
static uint32_t XXH_rotl32 (uint32_t const value, uint32_t amount) {
    uint32_t const mask = 31;
    amount &= mask;
    return (value << amount) | (value >> (-amount & mask));
}
```

For commentary, see: https://en.wikipedia.org/wiki/Circular_shift#Implementing_circular_shifts
(updated to remove `const` on `amount`).

**Comment by easyaspi314** [comment]
> "excessively?" clean

Nonsense :smirk:

That sounds like a good idea. Will add it when I get a chance.

**Comment by easyaspi314** [comment]
Thanks! I had already had a rotl implementation that avoided UB in XXH3, so I just had to port it over.

**Comment by weaversa** [comment]
The new rotl functions can exhibit UB when amt = 0.

```
$ make prove
clang xxhash32-ref.c -o xxhash32-ref.bc -c -emit-llvm -Wno-long-long -O1 -std=c90
clang xxhash64-ref.c -o xxhash64-ref.bc -c -emit-llvm -Wno-long-long -O1 -std=c90
saw saw/xxhash32.saw
[18:12:55.128] Loading file "xxhash-clean/saw/xxhash32.saw"
[18:12:55.130] Loading file "xxhash-clean/saw/llvm.saw"
[18:12:55.426] Verifying XXH_rotl32 ...
[18:12:55.426] Simulating XXH_rotl32 ...
[18:12:55.430] Checking proof obligations XXH_rotl32 ...
[18:12:55.439] Subgoal failed: XXH_rotl32 safety assertion:
LLVM Poison value created
The second operand of `lshr` was equal to or greater than the number of
bits in the first operand
in XXH_rotl32 at internal
Details:
Undefined behavior encountered: 
LLVM Poison value created
The second operand of `lshr` was equal to or greater than the number of
bits in the first operand
Reference: 
The LLVM language reference, version8
‘lshr’ Instruction (Semantics)
Document URL: https://llvm.org/docs/LangRef.html

[18:12:55.439] SolverStats {solverStatsSolvers = fromList ["SBV->Z3"], solverStatsGoalSize = 30}
[18:12:55.439] ----------Counterexample----------
[18:12:55.439]   amt: 0
[18:12:55.440] ----------------------------------
[18:12:55.440] Stack trace:
"llvm_verify" (xxhash-clean/saw/xxhash32.saw:41:22-41:33):
"crucible_llvm_verify" (xxhash-clean/saw/llvm.saw:37:3-37:23):
Proof failed.
make: *** [prove] Error 2
```

**Comment by tansy** [comment]
I don't think the problem comes from construction @weaversa (`return (value << amt) | (value >> (32 - amt));`) quoted. 
In fact, XXH_rotl32() is defined this way:

```
static uint32_t XXH_rotl32(uint32_t const value, uint32_t const amt)
{
    return (value << (amt % 32)) | (value >> (32 - amt % 32));
}
```
which is equivalent to use bitwise and (`amt & 31`) and share, at least theoretically/formally, the same problem - undefined behaviour (UB) when *amt = 0*.

In our case, XXH_rotl32() compiles, with optimizations (-O1, -O2)
`$ gcc -S -masm=intel -$OPT -c xxh_rotl32d.c`

to:

```
.LFB0:
    push    ebx
    mov     edx, DWORD PTR [esp+12]
    and     edx, 31
    mov     ecx, 32
    sub     ecx, edx
    mov     eax, DWORD PTR [esp+8]
    shr     eax, cl
    mov     ebx, DWORD PTR [esp+8]
    mov     cl, dl
    sal     ebx, cl
    or      eax, ebx
    pop
    ret
```

but if you worked as compiler for just a sec and changed the function to:
```
static uint32_t XXH_rotl32(uint32_t const value, uint32_t amt)
{
    uint32_t shift = amt % 32;
    return (value << (shift)) | (value >> (32 - shift));
}
```
which is essentially the same, that would make compilers job easier and result would be:

```
.LB0:
    mov     eax, DWORD PTR [esp+4]
    mov     ecx, DWORD PTR [esp+8]
    rol     eax, cl
    ret
```

just like the very basic, "unprotected" form:

```
static uint32_t XXH_rotl32(uint32_t const value, uint32_t const shift)
{
    return (value << (shift)) | (value >> (32 - shift));
}
```
```
.LFB0:
    mov     eax, DWORD PTR [esp+4]
    mov     ecx, DWORD PTR [esp+8]
    rol     eax, cl
    ret
```


But the problem roots from the construction not from UB itself because moderns compilers recognize this construction:
`(value << shift) | (value >> (32 - shift))`
and compile it to single `rol` instruction.
Just by replacing double modulo with `shift = amt % 32;` or even `shift = amt & 31;` (which is functional equivalent) boils it down to `(value << (shift)) | (value >> (32 - shift));` that is recognized by compilers for eons. My oldest one at the moment, gcc-4.7.2 from 2012 does recognize it.

So all you need to do to remove double modulo (or and for that matter) from return line and perform this operation before, or even remove it completely and count for compiler's ability to properly handle it. Moreover, it can easile be checked by compiling int assembler form and inspecting result.
 
If you are paranoid then even wikipedia's version would be better:
 
```
uint32_t wikipedia_rotl(uint32_t const value, uint32_t const amt)
{
    uint32_t shift = amt & 31;
    if ((shift) != 0)
        return (value << shift) | (value >> (32 - shift));
    return value;
}
```
 
as it compiles to:
 
```
.LFB0:
	mov	ecx, DWORD PTR [esp+8]
	mov	eax, DWORD PTR [esp+4]
	and	ecx, 31
	je	.L3
	rol	eax, cl
	ret
.L3:
	ret
```
which adds one comparison and one branch in 1/32 of cases and, obviously, does not cause undefined behaviour.

**Comment by 42Bastian** [comment]
Just my 2cents: ARM GCC 9.1.0 does recognize both versions and generates (identical) real nice code :-) 
 `  h32 = (XXH_rotl32(v1, 1) + XXH_rotl32(v2, 7) +
         XXH_rotl32(v3, 12) + XXH_rotl32(v4, 18));
`
=>
```  ror r4, r4, #25
 add r10, r4, r10, ror #31
 add r1, r1, r10
 add r9, r1, r7, ror #20
 ldr r0, .L13+12 
 add r8, r9, r6, ror #14
```

**Comment by weaversa** [comment]
Thank you for thinking about and commenting on this challenging (yet simple) function!

I've gathered the five different implementations of `rotl` found here. I then ran them head to head against each other with _surprising_ results (which you can see below). I'm using Apple's current version of `clang`.

I believe the results are surprising because the C -> LLVM pass uses an optimization technique (namely, constant propagation) that (correctly) triggers the undefined behavior of C's shift operator. However, (as mentioned here) the LLVM -> x86 transformation happens to make the shift operator total in such a way that our rotate functions work as we desire.

Since the point of the XXH reference code is to provide the community with (as @easyaspi314 says) "excessively" clean code, I suggest it be updated to include one of the implementations that doesn't have undefined behavior from the perspective of the language specification XXH is written in. This would avoid the possibility (demonstrated below) of a pedantic compiler pass blindly following the C language specification, rather than doing what you expect - choosing a way to _fix_ the undefined behavior that's specified in the C language spec.

```
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

static uint32_t XXH_rotl32(uint32_t const value, uint32_t const amt)
{
    return (value << (amt % 32)) | (value >> (32 - amt % 32));
}

static uint32_t XXH_rotl32_modified(uint32_t const value, uint32_t amt)
{
    uint32_t shift = amt % 32;
    return (value << (shift)) | (value >> (32 - shift));
}

static uint32_t XXH_rotl32_unprotected(uint32_t const value, uint32_t const shift)
{
    return (value << (shift)) | (value >> (32 - shift));
}

uint32_t wikipedia_rotl(uint32_t const value, uint32_t const amt)
{
    uint32_t shift = amt & 31;
    if ((shift) != 0)
        return (value << shift) | (value >> (32 - shift));
    return value;
}

static uint32_t wikipedia_rotl_alternate (uint32_t const value, uint32_t amount) {
    uint32_t const mask = 31;
    amount &= mask;
    return (value << amount) | (value >> (-amount & mask));
}

int main(int argc, char **argv) {

  uint32_t amt = atoi(argv[1]);

  fprintf(stdout, "XXH current constant propagate = 0x%x\n", XXH_rotl32(0x12345678, 32));
  fprintf(stdout, "XXH current variable = 0x%x\n", XXH_rotl32(0x12345678, amt));

  fprintf(stdout, "XXH modified constant propagate = 0x%x\n", XXH_rotl32_modified(0x12345678, 32));
  fprintf(stdout, "XXH modified variable = 0x%x\n", XXH_rotl32_modified(0x12345678, amt));

  fprintf(stdout, "XXH unprotected constant propagate = 0x%x\n", XXH_rotl32_unprotected(0x12345678, 32));
  fprintf(stdout, "XXH unprotected variable = 0x%x\n", XXH_rotl32_unprotected(0x12345678, amt));

  fprintf(stdout, "wiki constant propagate = 0x%x\n", wikipedia_rotl(0x12345678, 32));
  fprintf(stdout, "wiki variable = 0x%x\n", wikipedia_rotl(0x12345678, amt));

  fprintf(stdout, "wiki alternate constant propagate = 0x%x\n", wikipedia_rotl_alternate(0x12345678, 32));
  fprintf(stdout, "wiki alternate variable = 0x%x\n", wikipedia_rotl_alternate(0x12345678, amt));

  return 0;
}
```

```
$ clang --version
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.4.0
Thread model: posix
$ clang rot.c -o rot -O2 && ./rot 32
XXH current constant propagate = 0xffffffff
XXH current variable = 0x12345678
XXH modified constant propagate = 0xffffffff
XXH modified variable = 0x12345678
XXH unprotected constant propagate = 0xffffffff
XXH unprotected variable = 0x12345678
wiki constant propagate = 0x12345678
wiki variable = 0x12345678
wiki alternate constant propagate = 0x12345678
wiki alternate variable = 0x12345678
```
